version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: ai_analyst_nginx
    restart: always
    ports:
      - "8080:80"  # Expose standard HTTP port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
  # 1. Your FastAPI Backend
  backend:
    build: ./backend  # Looks for the Dockerfile in /backend folder
    container_name: ai_analyst_backend
    restart: always
    depends_on:
      - db
    environment:
      # Notice we use 'db' (the service name) instead of 'localhost'
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/temp_uploads:/app/temp_uploads

  # 2. The Database Service
  db:
    image: postgres:15-alpine
    container_name: ai_analyst_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ai_analytics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. The Database UI (Optional - disable in prod to save resources if needed)
  pgadmin:
    image: dpage/pgadmin4
    container_name: ai_analyst_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    #ports:
    #  - "5050:80"
    expose:
      - 80
    depends_on:
      - db

volumes:
  postgres_data: